version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: composer
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: github-actions
    target-branch: 'releases/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    target-branch: 'releases/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: composer
    target-branch: 'releases/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
