version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: composer
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: github-actions
    target-branch: 'release/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    target-branch: 'release/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: tailwindcss
        versions: [ '^4' ]

  - package-ecosystem: composer
    target-branch: 'release/v1'
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
